# Generated by Django 5.1.5 on 2025-01-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_organization_userinfo_about_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(default='user_profile_img/profile.webp', upload_to='user_profile_img'),
        ),
    ]
