# Generated by Django 5.1.5 on 2025-01-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_current_position_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('repo_link', models.URLField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='user-project-files')),
                ('tech_stack', models.ManyToManyField(blank=True, null=True, related_name='user_projects', to='myapp.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myapp.userinfo')),
            ],
        ),
    ]
