# Generated by Django 5.1.5 on 2025-01-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to='myapp.skill'),
        ),
    ]
