# Generated by Django 5.1.5 on 2025-01-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='project/thumbnail')),
                ('type', models.CharField(blank=True, choices=[('O', 'Open-Source'), ('F', 'Freelance'), ('P', 'Paid'), ('L', 'Learning')], max_length=1, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='project/files')),
                ('video', models.FileField(blank=True, null=True, upload_to='project/videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='myapp.userinfo')),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='joined_projects', to='myapp.userinfo')),
            ],
        ),
    ]
