# Generated by Django 5.1.5 on 2025-01-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_projects', to='myapp.userinfo'),
        ),
    ]
