# Generated by Django 5.1.5 on 2025-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_projects_github_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='skill_needed',
            field=models.ManyToManyField(blank=True, related_name='projects', to='myapp.skill'),
        ),
        migrations.AddField(
            model_name='projects',
            name='domain',
            field=models.ManyToManyField(blank=True, related_name='projects', to='myapp.domain'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='domains',
            field=models.ManyToManyField(blank=True, to='myapp.domain', verbose_name='developers'),
        ),
    ]
