# Generated by Django 5.1.5 on 2025-01-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_domain_projects_skill_needed_projects_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='domain',
        ),
        migrations.AddField(
            model_name='projects',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='myapp.domain'),
        ),
    ]
