# Generated by Django 5.1.5 on 2025-01-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_projects_domain_projects_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='level',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], max_length=1, null=True),
        ),
    ]
