# Generated by Django 5.1.5 on 2025-01-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_projects_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dev_story',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
