# Generated by Django 5.1.5 on 2025-02-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_userinfo_gender_alter_userinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
