# Generated by Django 5.1.5 on 2025-02-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_user_project_end_date_user_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
