# Generated by Django 5.1.5 on 2025-02-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_projects_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='myapp.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='myapp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='project_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.project_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_replies', to='myapp.userinfo')),
            ],
        ),
    ]
