# Generated by Django 5.1.5 on 2025-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_projects_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
