# Generated by Django 5.1.5 on 2025-02-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_user_status_userinfo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_reply',
            options={'verbose_name_plural': 'project_reply'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='user_status',
            options={'verbose_name_plural': 'user_status'},
        ),
        migrations.AddField(
            model_name='organization',
            name='discord',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
