# Generated by Django 5.1.5 on 2025-02-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_project_reply_options_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Private', 'Private Company'), ('Open', 'Open Organization'), ('Club', 'Club/Group'), ('Startup', 'Startup'), ('NonProfit', 'Non-Profit Organization'), ('Gov', 'Government Institution'), ('Education', 'Educational Institution'), ('Research', 'Research Lab')], default='Private', max_length=50),
        ),
    ]
