# Generated by Django 5.1.5 on 2025-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('Software', 'Software & IT Services'), ('AI_ML', 'Artificial Intelligence & Machine Learning'), ('Cloud', 'Cloud Computing & Infrastructure'), ('Cybersecurity', 'Cybersecurity'), ('Blockchain', 'Blockchain, Crypto & Web3'), ('GameDev', 'Game Development'), ('Fintech', 'Financial Technology (Fintech)'), ('EdTech', 'Education Technology'), ('HealthTech', 'Healthcare & Medical Technology'), ('Hardware', 'Hardware & Electronics'), ('Telecom', 'Telecommunications'), ('Ecommerce', 'E-commerce & Retail Tech'), ('Marketing', 'Marketing & Advertising Technology'), ('Media', 'Media & Entertainment'), ('Automotive', 'Automotive & Mobility Tech'), ('Aerospace', 'Aerospace & Defense'), ('IoT_Robotics', 'IoT, Robotics & Automation'), ('GreenTech', 'GreenTech & Sustainable Energy'), ('AR_VR', 'Augmented Reality & Virtual Reality'), ('Gov', 'Government & Public Sector'), ('Defense', 'Defense & Military'), ('LawEnforcement', 'Law Enforcement & Security'), ('PublicTransport', 'Public Transportation'), ('PublicHealth', 'Public Health & Safety'), ('HigherEd', 'Higher Education & Universities'), ('K12', 'K-12 Schools & Educational Institutions'), ('Research', 'Research & Development'), ('TechClub', 'Tech Clubs & Developer Communities'), ('Cultural_Sports', 'Cultural, Arts & Sports Organizations'), ('SocialClub', 'Social & Networking Clubs'), ('NonProfit', 'Non-Profit & Humanitarian Organizations'), ('Environmental', 'Environmental & Sustainability'), ('Startup', 'Startup & Entrepreneurship'), ('Consulting', 'IT & Business Consulting'), ('VentureCapital', 'Venture Capital & Investment'), ('Legal', 'Legal & Compliance Services'), ('SupplyChain', 'Supply Chain & Logistics'), ('RealEstate', 'Real Estate & Property Management'), ('Manufacturing', 'Manufacturing & Industrial Technology'), ('Agritech', 'Agriculture & Food Tech'), ('HumanResources', 'Human Resources & Talent Management'), ('Journalism', 'Journalism & Publishing'), ('Entertainment', 'Entertainment & Performing Arts'), ('Religion', 'Religious Organizations'), ('Hospitality', 'Hospitality & Tourism'), ('Other', 'Other')], default='TechClub', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='organization_logo'),
        ),
    ]
