# Generated by Django 5.1.5 on 2025-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_organization_industry_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='organization_logo/organization_logo.svg', upload_to='organization_logo'),
        ),
    ]
