# Generated by Django 5.1.5 on 2025-02-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_organization', to='myapp.userinfo'),
        ),
    ]
