# Generated by Django 5.1.5 on 2025-02-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_event_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('events', models.ManyToManyField(blank=True, related_name='saved_by_events', to='myapp.event')),
                ('posts', models.ManyToManyField(blank=True, related_name='saved_by_posts', to='myapp.post')),
                ('project', models.ManyToManyField(blank=True, related_name='saved_by_projects', to='myapp.projects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='myapp.userinfo')),
            ],
        ),
    ]
