# Generated by Django 5.1.5 on 2025-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_saveditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
