# Generated by Django 5.1.5 on 2025-02-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_education_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='till_now',
            field=models.BooleanField(default=False),
        ),
    ]
