# Generated by Django 5.1.5 on 2025-02-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_education_till_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='till_now',
            field=models.BooleanField(default=False),
        ),
    ]
