# Generated by Django 5.1.5 on 2025-02-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_experience_till_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='about_user',
        ),
    ]
