# Generated by Django 5.1.5 on 2025-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_rename_dev_story_userinfo_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
