# Generated by Django 5.1.5 on 2025-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_userinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=25, null=True),
        ),
    ]
