# Generated by Django 5.1.5 on 2025-02-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_comments',
            options={'verbose_name_plural': 'Post comments'},
        ),
        migrations.RenameField(
            model_name='post_comments',
            old_name='post',
            new_name='Post',
        ),
    ]
