# Generated by Django 5.1.5 on 2025-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_alter_post_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_comments',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Post comments'},
        ),
        migrations.AddField(
            model_name='post',
            name='aspect',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('1:1', '1:1'), ('16:9', '16:9')], default='ORIGINAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='user-posts'),
        ),
    ]
