# Generated by Django 5.1.5 on 2025-02-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_alter_post_comments_options_post_aspect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aspect',
            field=models.CharField(choices=[('Original', 'Original'), ('1:1', '1:1'), ('16:9', '16:9')], default='Original', max_length=10),
        ),
    ]
