# Generated by Django 5.1.5 on 2025-02-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_current_position_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_position',
            name='till_now',
            field=models.BooleanField(default=False),
        ),
    ]
