# Generated by Django 5.1.5 on 2025-03-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_event_contact_email_event_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(null=True, upload_to='user-posts'),
        ),
    ]
