# Generated by Django 5.1.5 on 2025-03-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, default='events/default-event-banner.png', help_text='Optional Banner for the event.', null=True, upload_to='events'),
        ),
    ]
