# Generated by Django 5.1.5 on 2025-03-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_event_comment_event_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
