# Generated by Django 5.1.5 on 2025-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_event_end_date_event_start_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
