# Generated by Django 5.1.5 on 2025-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_userinfo_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(blank=True, choices=[('Open-Source', 'Open-Source'), ('Freelance', 'Freelance'), ('Paid', 'Paid'), ('Learning', 'Learning')], max_length=50, null=True),
        ),
    ]
