# Generated by Django 5.1.5 on 2025-03-19 13:26

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_alter_organization_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
