# Generated by Django 5.1.5 on 2025-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_alter_experience_role_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
