# Generated by Django 5.1.5 on 2025-03-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_notification_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projects'),
        ),
        migrations.AddField(
            model_name='notification',
            name='project_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.project_comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='project_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.project_reply'),
        ),
    ]
