# Generated by Django 5.1.5 on 2025-03-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_notification_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='industry',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Liked your post'), ('comment', 'Commented on your post'), ('follow', 'Started following you'), ('Join_Project', 'Joined On Your Project'), ('project_comment', 'Commented on Your project')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('Private', 'Private Company'), ('Open', 'Open Organization'), ('Club-Groups', 'Club/Group'), ('Startup', 'Startup'), ('NonProfit', 'Non-Profit Organization'), ('Gov', 'Government Institution'), ('Education', 'Educational Institution'), ('Research Lab', 'Research Lab')], default='Private', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='myapp.industry'),
        ),
    ]
