# Generated by Django 5.1.5 on 2025-03-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CringeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('emoji', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Liked your post'), ('comment', 'Commented on your post'), ('follow', 'Started following you'), ('Join_Project', 'Joined On Your Project'), ('project_comment', 'Commented on Your project'), ('project_reply', 'Replied to your Comment')], max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cringe_badge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='myapp.cringebadge'),
        ),
    ]
