# Generated by Django 5.1.5 on 2025-03-31 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_cringebadge_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cringe_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='myapp.cringebadge'),
        ),
    ]
