# Generated by Django 5.1.5 on 2025-05-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_alter_userinfo_cringe_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='timezone',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
