# Generated by Django 5.1.5 on 2025-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_remove_userinfo_timezone_userinfo_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
