# Generated by Django 5.1.5 on 2025-05-10 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_userinfo_created_at_userinfo_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['created_at'], name='myapp_useri_created_d0651d_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['updated_at'], name='myapp_useri_updated_9f35be_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['profile_views'], name='myapp_useri_profile_eb9b09_idx'),
        ),
    ]
