# Generated by Django 5.1.5 on 2025-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_userinfo_myapp_useri_created_d0651d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userinfo',
            name='myapp_useri_created_d0651d_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinfo',
            name='myapp_useri_updated_9f35be_idx',
        ),
        migrations.RemoveIndex(
            model_name='userinfo',
            name='myapp_useri_profile_eb9b09_idx',
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
