# Generated by Django 5.1.5 on 2025-05-11 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_remove_userinfo_myapp_useri_created_d0651d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
