# Generated by Django 5.1.5 on 2025-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0086_alter_userinfo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
