# Generated by Django 5.1.5 on 2025-05-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0088_userinfo_needs_profile_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(default='user_profile_img/profile.jpg', upload_to='user_profile_img'),
        ),
    ]
