# Generated by Django 5.1.5 on 2025-05-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0089_alter_userinfo_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.event_comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.event_reply'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Liked your post'), ('comment', 'Commented on your post'), ('follow', 'Started following you'), ('Join_Project', 'Joined On Your Project'), ('project_comment', 'Commented on Your project'), ('project_reply', 'Replied to your Comment'), ('event_comment', 'Commented on your Event'), ('event_reply', 'Replied to your Comment')], max_length=50),
        ),
    ]
