# Generated by Django 5.1.5 on 2025-05-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0090_notification_event_comment_notification_event_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='organization_logo/org-logo.png', upload_to='organization_logo'),
        ),
    ]
