# Generated by Django 5.1.5 on 2025-05-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0091_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
