# Generated by Django 5.1.5 on 2025-05-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0092_organization_profile_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='profile_views',
            new_name='profile_views_followers',
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_views_nonfollowers',
            field=models.IntegerField(default=0),
        ),
    ]
