# Generated by Django 5.2.1 on 2025-05-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0095_alter_event_uuid_alter_projects_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='profile_views_followers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_views_nonfollowers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
