# Generated by Django 5.2.1 on 2025-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0096_alter_organization_profile_views_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
