# Generated by Django 5.2.1 on 2025-05-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0097_alter_userinfo_profile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='availability',
            field=models.CharField(blank=True, choices=[('Available', 'Available for collaboration'), ('part-time', 'Open to part-time collaboration'), ('freelance', 'Open to freelance collaboration'), ('Unavailable', 'Unavailable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
