# Generated by Django 5.2.1 on 2025-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0098_alter_userinfo_availability_alter_userinfo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='availability',
            field=models.CharField(blank=True, choices=[('available', 'Available for collaboration'), ('part-time', 'Open to part-time collaboration'), ('freelance', 'Open to freelance collaboration'), ('unavailable', 'Unavailable')], max_length=50, null=True),
        ),
    ]
