# Generated by Django 5.2.1 on 2025-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0099_alter_userinfo_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(upload_to='user-posts'),
        ),
    ]
