# Generated by Django 5.2.1 on 2025-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0101_alter_user_project_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
