# Generated by Django 5.2.1 on 2025-05-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0103_organization_updated_at_alter_userinfo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
