# Generated by Django 5.2.1 on 2025-05-30 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0104_userinfo_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
