# Generated by Django 5.2.1 on 2025-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0105_alter_userinfo_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_event_comment', to='myapp.userinfo'),
        ),
        migrations.AddField(
            model_name='event_reply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_event_reply', to='myapp.userinfo'),
        ),
        migrations.AddField(
            model_name='project_comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_project_comment', to='myapp.userinfo'),
        ),
        migrations.AddField(
            model_name='project_reply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_project_reply', to='myapp.userinfo'),
        ),
    ]
