# Generated by Django 5.2.1 on 2025-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0106_event_comment_likes_event_reply_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Liked your post'), ('comment', 'Commented on your post'), ('follow', 'Started following you'), ('Join_Project', 'Joined On Your Project'), ('project_comment', 'Commented on Your project'), ('project_reply', 'Replied to your Comment'), ('event_comment', 'Commented on your Event'), ('event_reply', 'Replied to your Comment'), ('project_comment_like', 'Liked your comment on Project'), ('event_comment_like', 'Liked your comment on Event')], max_length=50),
        ),
    ]
