# Generated by Django 5.2.1 on 2025-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0107_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Liked your post'), ('comment', 'Commented on your post'), ('follow', 'Started following you'), ('Join_Project', 'Joined On Your Project'), ('project_comment', 'Commented on Your project'), ('project_reply', 'Replied to your Comment'), ('event_comment', 'Commented on your Event'), ('event_reply', 'Replied to your Comment'), ('project_comment_like', '❤️ your comment on Project'), ('event_comment_like', '❤️ your comment on Event')], max_length=50),
        ),
    ]
