# Generated by Django 5.2.1 on 2025-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0108_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='rejected_users',
            field=models.ManyToManyField(blank=True, related_name='rejected_projects', to='myapp.userinfo'),
        ),
        migrations.AddField(
            model_name='projects',
            name='requested_users',
            field=models.ManyToManyField(blank=True, related_name='requested_projects', to='myapp.userinfo'),
        ),
    ]
