# Generated by Django 5.2.1 on 2025-06-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0109_projects_rejected_users_projects_requested_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Liked your post'), ('comment', 'Commented on your post'), ('follow', 'Started following you'), ('Join_Project', 'Requested to Join Your Project'), ('accept_member_project', 'Congratulations! You’ve been accepted to join'), ('reject_member_project', 'We’re sorry, your join request has been rejected for'), ('project_comment', 'Commented on Your project'), ('project_reply', 'Replied to your Comment'), ('event_comment', 'Commented on your Event'), ('event_reply', 'Replied to your Comment'), ('project_comment_like', '❤️ your comment on Project'), ('event_comment_like', '❤️ your comment on Event')], max_length=50, null=True),
        ),
    ]
