# Generated by Django 5.2.1 on 2025-06-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0105_alter_userinfo_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('week_start', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_leaderboard', to='myapp.userinfo')),
            ],
            options={
                'ordering': ['-score', 'user__user__username'],
            },
        ),
    ]
