# Generated by Django 5.2.1 on 2025-06-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('myapp', '0105_alter_userinfo_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingleaderboard',
            name='actions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendingleaderboard',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendingleaderboard',
            name='projects_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='trendingleaderboard',
            index=models.Index(fields=['week_start'], name='features_tr_week_st_1abeee_idx'),
        ),
    ]
